### ISSUE TITLE
Critical Error After updating to 7.2.3

### ISSUE THREAD

**Issue by rezetta** [mattpugh/WHMCS#1]
This is very disappointing. After upgrade I am experiencing issues!

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'category_id' cannot be null (SQL: insert into `tbltld_category_pivot` (`tld_id`, `category_id`, `created_at`, `updated_at`) values (1, , 2017-08-01 12:44:23, 2017-08-01 12:44:23)).

I have tried to insert the data into our tables manually, but this did not solve the issue. So now our site is down!

**Comment by mattpugh** [comment]
From the error, it looks like you might have gotten SQL strict mode enabled on your server. But if you want to get in touch with our support team, they'll be happy to assist you.

https://www.whmcs.com/support

**Comment by rezetta** [comment]
This issue is occurring because tbltld_categories table is empty. I had to populate the table with correct data to make this work.
